import ImgCar from "../../assets/images/car_police.png"

export const carList = [
  {
    img:ImgCar,
    name:"Lexus 4203",
    detail1:"Police Engine",
    detail2:"Police Engine",
    detail3:"Police Engine",
  },
  {
    img:ImgCar,
    name:"Lexus 4203",
    detail1:"Police Engine",
    detail2:"Police Engine",
    detail3:"Police Engine",
  },
  {
    img:ImgCar,
    name:"Lexus 4203",
    detail1:"Police Engine",
    detail2:"Police Engine",
    detail3:"Police Engine",
  },
  {
    img:ImgCar,
    name:"Lexus 4203",
    detail1:"Police Engine",
    detail2:"Police Engine",
    detail3:"Police Engine",
  },
  {
    img:ImgCar,
    name:"Lexus 4203",
    detail1:"Police Engine",
    detail2:"Police Engine",
    detail3:"Police Engine",
  },
  {
    img:ImgCar,
    name:"Lexus 4203",
    detail1:"Police Engine",
    detail2:"Police Engine",
    detail3:"Police Engine",
  },
  {
    img:ImgCar,
    name:"Lexus 4203",
    detail1:"Police Engine",
    detail2:"Police Engine",
    detail3:"Police Engine",
  },
  {
    img:ImgCar,
    name:"Lexus 4203",
    detail1:"Police Engine",
    detail2:"Police Engine",
    detail3:"Police Engine",
  },
  {
    img:ImgCar,
    name:"Lexus 4203",
    detail1:"Police Engine",
    detail2:"Police Engine",
    detail3:"Police Engine",
  },
  {
    img:ImgCar,
    name:"Lexus 4203",
    detail1:"Police Engine",
    detail2:"Police Engine",
    detail3:"Police Engine",
  },
  {
    img:ImgCar,
    name:"Lexus 4203",
    detail1:"Police Engine",
    detail2:"Police Engine",
    detail3:"Police Engine",
  },
  {
    img:ImgCar,
    name:"Lexus 4203",
    detail1:"Police Engine",
    detail2:"Police Engine",
    detail3:"Police Engine",
  },
  {
    img:ImgCar,
    name:"Lexus 4203",
    detail1:"Police Engine",
    detail2:"Police Engine",
    detail3:"Police Engine",
  },
  {
    img:ImgCar,
    name:"Lexus 4203",
    detail1:"Police Engine",
    detail2:"Police Engine",
    detail3:"Police Engine",
  },
  {
    img:ImgCar,
    name:"Lexus 4203",
    detail1:"Police Engine",
    detail2:"Police Engine",
    detail3:"Police Engine",
  },
  {
    img:ImgCar,
    name:"Lexus 4203",
    detail1:"Police Engine",
    detail2:"Police Engine",
    detail3:"Police Engine",
  },
  {
    img:ImgCar,
    name:"Lexus 4203",
    detail1:"Police Engine",
    detail2:"Police Engine",
    detail3:"Police Engine",
  },
  {
    img:ImgCar,
    name:"Lexus 4203",
    detail1:"Police Engine",
    detail2:"Police Engine",
    detail3:"Police Engine",
  },
]